### ISSUE TITLE
[Improvement]: Inaccurate translation

### ISSUE THREAD

**Issue by HerbertHe** [Next2D/tool.next2d.app#11]
I have experienced the tool at [NoCode Tool Website](https://tool.next2d.app), but I found the tool translation of Chinese version is not inaccurate! When I wanted to help to fix this issue, I found that this repo seems to be generated and I could not find the source code :(

**Comment by ienaga** [comment]
@HerbertHe 
Sorry for the late reply.
The source is too cumbersome for me. I'll publish it when it's webpack compatible.

**Comment by HerbertHe** [comment]
@ienaga 
I see... 
I am waiting for the update~

**Comment by ienaga** [comment]
@HerbertHe 

It was going to take some time to prepare, so we have moved it to this repository.
https://github.com/Next2D/tool-language

I would be happy if you could take a look at it when you have time.

**Comment by HerbertHe** [comment]
🌚ok，got it~ I am always here

**Comment by ienaga** [comment]
Thanks!!
