### ISSUE TITLE
SWF import still working for you?

### ISSUE THREAD

**Issue by j2l** [Next2D/tool.next2d.app#148]
Hello,
It seems promising, congrats!
I watched your video and you import SWF file content.
I'm working on linux (ubuntu 22.04) and tried https://tool.next2d.app/ but cannot import any swf
See enclosed swf
[custom.bg.bedroom_bg.swf.zip](https://github.com/user-attachments/files/17493538/custom.bg.bedroom_bg.swf.zip)

**Comment by ienaga** [comment]
@j2l 

Hello,
Thank you for contacting me.

Only Shape and Bitmap are supported now.
We may support text and video in the future, but we have no plans to support ActionScript.

Is this the answer to your question?

**Comment by j2l** [comment]
Thank you @ienaga 
Yes, it totally makes sense. 
I guess the SWF is bad, since it has "bad signature" when I try to open it elsewhere.
I didn't generate this SWF, so I can't tell if it has action script, it should only have Bitmap and/or shape, but I'm not sure.
